import { writeFileSync } from "fs";

const LADDERS = [
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder11.html", label: "A2OJ <1300" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder12.html", label: "A2OJ 1300-1399" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder13.html", label: "A2OJ 1400-1499" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder14.html", label: "A2OJ 1500-1599" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder15.html", label: "A2OJ 1600-1699" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder16.html", label: "A2OJ 1700-1799" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder17.html", label: "A2OJ 1800-1899" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder18.html", label: "A2OJ 1900-1999" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder19.html", label: "A2OJ 2000-2099" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder20.html", label: "A2OJ 2100-2199" },
  { url: "https://earthshakira.github.io/a2oj-clientside/server/Ladder21.html", label: "A2OJ >=2200" },
];

const RE = /problemset\/problem\/(\d+)\/([A-Z]\d?)/g;

async function fetchLadder({ url, label }) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const html = await res.text();
  const problems = [];
  let m;
  RE.lastIndex = 0;
  while ((m = RE.exec(html)) !== null) {
    problems.push(`${m[1]}-${m[2]}`);
  }
  console.log(`  ${label}: ${problems.length} problems`);
  return { label, problems };
}

const results = await Promise.all(LADDERS.map(fetchLadder));

// Build map: first label wins (lowest-rated ladder)
const map = new Map();
for (const { label, problems } of results) {
  for (const key of problems) {
    if (!map.has(key)) map.set(key, label);
  }
}

console.log(`\nTotal unique entries: ${map.size}`);

const entries = [...map.entries()]
  .map(([k, v]) => `  ["${k}", "${v}"]`)
  .join(",\n");

const output = `// Auto-generated by scripts/buildCuratedProblems.mjs
// ${map.size} unique problems from A2OJ ladders (deduped, lowest-rated ladder label wins)
export const CURATED_PROBLEMS = new Map([
${entries},
]);
`;

writeFileSync("src/curatedProblems.js", output, "utf8");
console.log("Written: src/curatedProblems.js");
